#!/bin/bash
export proj_dir="/90daydata/beenome100/hesperapis_oraria_genomics/Gulf-Coast-bee2"
export my_code="/90daydata/beenome100/hesperapis_oraria_genomics/Gulf-Coast-bee2/code"
export my_data="/90daydata/beenome100/hesperapis_oraria_genomics/Gulf-Coast-bee2/data"
export my_results="/90daydata/beenome100/hesperapis_oraria_genomics/Gulf-Coast-bee2/results"
export my_softwares="/90daydata/beenome100/hesperapis_oraria_genomics/Gulf-Coast-bee2/softwares"
export my_docs="/90daydata/beenome100/hesperapis_oraria_genomics/Gulf-Coast-bee2/docs"
export meta_data="/90daydata/beenome100/hesperapis_oraria_genomics/Gulf-Coast-bee2/data/Samples.Metadata.csv"
export r_library="/90daydata/beenome100/hesperapis_oraria_genomics/Gulf-Coast-bee2/softwares/R_Packages/"
export ref_genome="/90daydata/beenome100/hesperapis_oraria_genomics/Gulf-Coast-bee2/data/reference_genome/Hesperapis_oraria_2.curatedScaff.clean_sort_rename_nuc.fasta"
export LR_VC_code="/90daydata/beenome100/hesperapis_oraria_genomics/Gulf-Coast-bee2/code/Long_read_Variant_Calling/"
export LR_VC_data="/90daydata/beenome100/hesperapis_oraria_genomics/Gulf-Coast-bee2/data/"
export LR_VC_results="/90daydata/beenome100/hesperapis_oraria_genomics/Gulf-Coast-bee2/results/Long_read_Variant_Calling/"
