#!/bin/bash
export proj_dir="/project/90daydata/beenome100/hesperapis_oraria_genomics/Test.Hesperapis_oraria_Pop_genomics"
export my_code="/project/90daydata/beenome100/hesperapis_oraria_genomics/Test.Hesperapis_oraria_Pop_genomics/code"
export my_data="/project/90daydata/beenome100/hesperapis_oraria_genomics/Test.Hesperapis_oraria_Pop_genomics/data"
export my_results="/project/90daydata/beenome100/hesperapis_oraria_genomics/Test.Hesperapis_oraria_Pop_genomics/results"
export my_softwares="/project/90daydata/beenome100/hesperapis_oraria_genomics/Test.Hesperapis_oraria_Pop_genomics/softwares"
export my_docs="/project/90daydata/beenome100/hesperapis_oraria_genomics/Test.Hesperapis_oraria_Pop_genomics/docs"
export meta_data="/project/90daydata/beenome100/hesperapis_oraria_genomics/Test.Hesperapis_oraria_Pop_genomics/data/Samples.Metadata.csv"
export r_library="/project/90daydata/beenome100/hesperapis_oraria_genomics/Test.Hesperapis_oraria_Pop_genomics/softwares/R_Packages/"
export ref_genome="/project/90daydata/beenome100/hesperapis_oraria_genomics/Test.Hesperapis_oraria_Pop_genomics/data/reference_genome/Hesperapis_oraria_2.curatedScaff.clean_sort_rename_nuc.fasta"
export VC_code="/project/90daydata/beenome100/hesperapis_oraria_genomics/Test.Hesperapis_oraria_Pop_genomics/code/Variant_Calling/"
export VC_data="/project/90daydata/beenome100/hesperapis_oraria_genomics/Test.Hesperapis_oraria_Pop_genomics/data/"
export VC_results="/project/90daydata/beenome100/hesperapis_oraria_genomics/Test.Hesperapis_oraria_Pop_genomics/results/Variant_Calling/"
